-- 유저 생성
CREATE USER TOUR
IDENTIFIED BY TOUR
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp;
-- 권한 설정
GRANT CONNECT TO TOUR;
GRANT RESOURCE TO TOUR;
GRANT dba TO TOUR;
GRANT CREATE TABLE TO TOUR;
ALTER USER TOUR DEFAULT TABLESPACE USERS;
